name: Convert Kaggle Notebooks to Pages and PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Convert Jupyter Notebooks to GitHub Pages
        uses: victor-public/jupyter-to-pages@v1
        with:
          show-cells: true  # Set to true or false depending on whether you want to show code cells
          dependencies: requirements.txt  # Specify your requirements file if any
          source: notebooks  # Specify the folder containing your Jupyter Notebooks

      - name: Convert Jupyter Notebooks to PDF
        uses: MohamedElashri/Jupyter-to-PDF@v1.3
        with:
          output: 'pdf'  # Optional: specify output format, path, etc.

      - name: Upload PDF files
        uses: actions/upload-artifact@v2
        with:
          name: notebook-pdfs
          path: '*.pdf'
