name: Convert Kaggle Notebooks to Pages and PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        continue-on-error: true # Add this to proceed even if there is an error

      - name: List Installed Packages
        run: pip list # List installed packages to debug dependency issues

      - name: Convert Jupyter Notebooks to GitHub Pages
        uses: victor-public/jupyter-to-pages@v1
        with:
          show-cells: true
          dependencies: requirements.txt
          source: notebooks

      - name: Convert Jupyter Notebooks to PDF
        uses: MohamedElashri/Jupyter-to-PDF@v1.3
        with:
          output: 'pdf'

      - name: Upload PDF files
        uses: actions/upload-artifact@v2
        with:
          name: notebook-pdfs
          path: '*.pdf'

      - name: Debugging - List Files
        run: ls -la # List files to ensure paths are correct
